### ISSUE TITLE
Contract client doesn't work for GET endpoints

### ISSUE THREAD

**Issue by Omegaice** [SIMBAChain/libsimba#5]
Due to the `SimbaContract` class validating parameters, it is not usable to query data added via a method call. I expected the following to be valid:

```python
AppID = "APP"
ContractName = "Contract"
MethodName = "Method"

results = await Simba().call_contract_method(
  app_id = AppID,
  contract_name = ContractName,
  method_name = MethodName,
  args = MethodCallArgs(args={"limit": 10})
)

results_client = await Simba().smart_contract_client(AppID,ContractName).call_method(
  method_name = MethodName,
  args = MethodCallArgs(args={"limit": 10})
)

assert results == results_client
```

**Comment by doctor-zob** [comment]
Do you have the signature of the `Method` method?

**Comment by Omegaice** [comment]
This is the metadata for the method. However, I am not trying to post new data to it, I just want to get results that have been posted to it. 

```json
"addNewPrinter": {
    "emits": [
        "EventNewPrinterAdded"
    ],
    "params": [
        {
            "name": "_name",
            "type": "string"
        },
        {
            "name": "_jsonDetails",
            "type": "string"
        }
    ],
    "returns": [],
    "accessor": false,
    "visibility": "external"
},
```

**Comment by doctor-zob** [comment]
Gotcha. So `call_method` calls a getter function on the contract, i.e., a function that doesn't result in a transaction on chain but instead is querying the contract state. In this case `accessor` is true. To query for transactions created by that function use `get_method_transactions` on the contract object, or `get_transactions_by_method` on the simba object. This accepts a `SearchFilter` to filter results.

**Comment by Omegaice** [comment]
Ahh, thanks for the information and quick response. I seem to have not read the documentation as well as I thought 😓.
